name: CI

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    name: rust (fmt, clippy, test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Rust toolchain
        run: rustup toolchain install
      - uses: Swatinem/rust-cache@f0deed1e0d78e4c9e5de6cf1919fcc6175a16312 # v2.7.7
      - name: Check, lint and test
        run: just check

  wasm:
    name: wasm (wasm-pack build)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Rust toolchain
        run: rustup toolchain install
      - uses: Swatinem/rust-cache@f0deed1e0d78e4c9e5de6cf1919fcc6175a16312 # v2.7.7
      - name: Install wasm-pack
        run: cargo install wasm-pack --locked
      - name: Build wasm target
        run: just wasm-build
